In [8]:
import numpy as np
import pandas as pd

### 传入loc的切片在python中是特殊情况，**包含右边**
eg：df.loc[1:3, "Party" : "%"]  # 包含1、2、3行和%列

### 传入iloc的切片在python中是常规情况，**不包含右边**

In [9]:
elections = pd.read_csv("data/elections.csv")
elections.head()

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789

In [10]:
elections.iloc[1:3, 1]

1    John Quincy Adams
2       Andrew Jackson
Name: Candidate, dtype: object

In [11]:
elections.loc[1:3, "Party": "%"]

                   Party  Popular vote Result          %
1  Democratic-Republican        113142    win  42.789878
2             Democratic        642806    win  56.203927
3    National Republican        500897   loss  43.796073

### 上下文依赖提取[]，结合loc和iloc，只接受一个参数：行号的切片、列标签的列表、单独的列标签
要么对行进行过滤，要么对列进行过滤<br>
传入的是整数或整数切片时，认为是行标签<br>
传入的是字符串时，认为是列标签<br>
这里的切片是不包含右边的

In [12]:
elections[['Year' , 'Party']]  # 列标签切片

     Year                  Party
0    1824  Democratic-Republican
1    1824  Democratic-Republican
2    1828             Democratic
3    1828    National Republican
4    1832             Democratic
..    ...                    ...
177  2016                  Green
178  2020             Democratic
179  2020             Republican
180  2020            Libertarian
181  2020                  Green

[182 rows x 2 columns]

In [13]:
import urllib.request
import os.path
import zipfile

data_url = "https://www.ssa.gov/oact/babynames/state/namesbystate.zip"
local_filename = "data/babynamesbystate.zip"
if not os.path.exists(local_filename): # If the data exists don't download again
    with urllib.request.urlopen(data_url) as resp, open(local_filename, 'wb') as f:
        f.write(resp.read())

zf = zipfile.ZipFile(local_filename, 'r')

ca_name = 'STATE.CA.TXT'
field_names = ['State', 'Sex', 'Year', 'Name', 'Count']
with zf.open(ca_name) as fh:
    babynames = pd.read_csv(fh, header=None, names=field_names)

babynames.head()

  State Sex  Year      Name  Count
0    CA   F  1910      Mary    295
1    CA   F  1910     Helen    239
2    CA   F  1910   Dorothy    220
3    CA   F  1910  Margaret    163
4    CA   F  1910   Frances    134

## 条件提取
可以把条件的布尔序列传递给.loc和上下文依赖提取的[]操作符